--------------------------------------------------------
--  File created - Wednesday-August-01-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "VAISHALI"."CUSTOMER" 
   (	"CUSTOMER_ID" NUMBER(5,0), 
	"CUSTOMER_NAME" VARCHAR2(50 BYTE), 
	"CUSTOMER_PH" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"SSN" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "VAISHALI"."EMPLOYEE" 
   (	"EMPLOYEE_ID" NUMBER(5,0), 
	"EMPLOYEE_NAME" VARCHAR2(50 BYTE), 
	"PHONE_NO" VARCHAR2(20 BYTE), 
	"JOB_TITLE" VARCHAR2(20 BYTE), 
	"EMPLOYEE_ADDRESS" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FARE
--------------------------------------------------------

  CREATE TABLE "VAISHALI"."FARE" 
   (	"ROUTE_ID" NUMBER(5,0), 
	"ECONOMY_FARE" FLOAT(10), 
	"BUSINESS_FARE" FLOAT(10), 
	"PLANE_TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FLIGHT
--------------------------------------------------------

  CREATE TABLE "VAISHALI"."FLIGHT" 
   (	"FLIGHT_ID" NUMBER(5,0), 
	"ROUTE_ID" NUMBER(5,0), 
	"PLANE_ID" NUMBER(5,0), 
	"ARR_TIME" DATE, 
	"DEPT_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLANE
--------------------------------------------------------

  CREATE TABLE "VAISHALI"."PLANE" 
   (	"PLANE_TYPE" VARCHAR2(20 BYTE), 
	"PLANE_ID" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROUTE
--------------------------------------------------------

  CREATE TABLE "VAISHALI"."ROUTE" 
   (	"ROUTE_ID" NUMBER(5,0), 
	"STARTING_FROM" VARCHAR2(20 BYTE), 
	"DESTINATION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SEATING
--------------------------------------------------------

  CREATE TABLE "VAISHALI"."SEATING" 
   (	"SEAT_NO" VARCHAR2(20 BYTE), 
	"FLIGHT_ID" NUMBER(5,0), 
	"DEPT_TIME" DATE, 
	"STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TICKET
--------------------------------------------------------

  CREATE TABLE "VAISHALI"."TICKET" 
   (	"TICKET_ID" NUMBER(5,0), 
	"CUSTOMER_ID" NUMBER(5,0), 
	"FLIGHT_ID" NUMBER(5,0), 
	"SEAT_NO" VARCHAR2(20 BYTE), 
	"DOJ" DATE, 
	"STATUS" VARCHAR2(20 BYTE), 
	"TOB" DATE, 
	"PASSENGER" VARCHAR2(20 BYTE), 
	"SSN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence BOOKING_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VAISHALI"."BOOKING_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CUSTOMER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VAISHALI"."CUSTOMER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence EMPLOYEE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VAISHALI"."EMPLOYEE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence FLIGHT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VAISHALI"."FLIGHT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PLANE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VAISHALI"."PLANE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PLANE_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "VAISHALI"."PLANE_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ROUTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VAISHALI"."ROUTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TICKET_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VAISHALI"."TICKET_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
REM INSERTING into VAISHALI.CUSTOMER
SET DEFINE OFF;
Insert into VAISHALI.CUSTOMER (CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_PH,EMAIL,SSN,ADDRESS,PASSWORD) values (1,'Vaishali','1111111111','das@gmail.com','1234',null,'das');
REM INSERTING into VAISHALI.EMPLOYEE
SET DEFINE OFF;
REM INSERTING into VAISHALI.FARE
SET DEFINE OFF;
Insert into VAISHALI.FARE (ROUTE_ID,ECONOMY_FARE,BUSINESS_FARE,PLANE_TYPE) values (1,4000,6000,'small');
REM INSERTING into VAISHALI.FLIGHT
SET DEFINE OFF;
Insert into VAISHALI.FLIGHT (FLIGHT_ID,ROUTE_ID,PLANE_ID,ARR_TIME,DEPT_TIME) values (1,1,1,to_date('02-AUG-18','DD-MON-RR'),to_date('02-AUG-18','DD-MON-RR'));
Insert into VAISHALI.FLIGHT (FLIGHT_ID,ROUTE_ID,PLANE_ID,ARR_TIME,DEPT_TIME) values (2,1,2,to_date('02-AUG-18','DD-MON-RR'),to_date('02-AUG-18','DD-MON-RR'));
REM INSERTING into VAISHALI.PLANE
SET DEFINE OFF;
Insert into VAISHALI.PLANE (PLANE_TYPE,PLANE_ID) values ('small',1);
Insert into VAISHALI.PLANE (PLANE_TYPE,PLANE_ID) values ('small',2);
REM INSERTING into VAISHALI.ROUTE
SET DEFINE OFF;
Insert into VAISHALI.ROUTE (ROUTE_ID,STARTING_FROM,DESTINATION) values (1,'HYD','DEL');
REM INSERTING into VAISHALI.SEATING
SET DEFINE OFF;
REM INSERTING into VAISHALI.TICKET
SET DEFINE OFF;
Insert into VAISHALI.TICKET (TICKET_ID,CUSTOMER_ID,FLIGHT_ID,SEAT_NO,DOJ,STATUS,TOB,PASSENGER,SSN) values (1,1,1,'B1',to_date('02-AUG-18','DD-MON-RR'),'booked',null,'Vaishali','1234');
Insert into VAISHALI.TICKET (TICKET_ID,CUSTOMER_ID,FLIGHT_ID,SEAT_NO,DOJ,STATUS,TOB,PASSENGER,SSN) values (1,1,1,'E1',to_date('02-AUG-18','DD-MON-RR'),'booked',null,'Ankusha','5678');
--------------------------------------------------------
--  DDL for Index BOOKING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VAISHALI"."BOOKING_PK" ON "VAISHALI"."TICKET" ("TICKET_ID", "CUSTOMER_ID", "PASSENGER", "SSN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VAISHALI"."CUSTOMER_PK" ON "VAISHALI"."CUSTOMER" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VAISHALI"."EMPLOYEE_PK" ON "VAISHALI"."EMPLOYEE" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "VAISHALI"."EMPLOYEE_UK1" ON "VAISHALI"."EMPLOYEE" ("PHONE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FARE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VAISHALI"."FARE_PK" ON "VAISHALI"."FARE" ("ROUTE_ID", "PLANE_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FLIGHT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VAISHALI"."FLIGHT_PK" ON "VAISHALI"."FLIGHT" ("FLIGHT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PLANE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VAISHALI"."PLANE_PK" ON "VAISHALI"."PLANE" ("PLANE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROUTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VAISHALI"."ROUTE_PK" ON "VAISHALI"."ROUTE" ("ROUTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SEATING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VAISHALI"."SEATING_PK" ON "VAISHALI"."SEATING" ("SEAT_NO", "FLIGHT_ID", "DEPT_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" 
  PARALLEL ;
--------------------------------------------------------
--  DDL for Trigger BOOKING_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "VAISHALI"."BOOKING_TRG" 
BEFORE INSERT ON "TICKET" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VAISHALI"."BOOKING_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CUSTOMER_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "VAISHALI"."CUSTOMER_TRG" 
BEFORE INSERT ON CUSTOMER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VAISHALI"."CUSTOMER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPLOYEE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "VAISHALI"."EMPLOYEE_TRG" 
BEFORE INSERT ON EMPLOYEE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VAISHALI"."EMPLOYEE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FLIGHT_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "VAISHALI"."FLIGHT_TRG" 
BEFORE INSERT ON FLIGHT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.FLIGHT_ID IS NULL THEN
      SELECT FLIGHT_SEQ.NEXTVAL INTO :NEW.FLIGHT_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VAISHALI"."FLIGHT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PLANE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "VAISHALI"."PLANE_TRG" 
BEFORE INSERT ON PLANE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VAISHALI"."PLANE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PLANE_TRG1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "VAISHALI"."PLANE_TRG1" 
BEFORE INSERT ON PLANE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PLANE_ID IS NULL THEN
      SELECT PLANE_SEQ1.NEXTVAL INTO :NEW.PLANE_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VAISHALI"."PLANE_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ROUTE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "VAISHALI"."ROUTE_TRG" 
BEFORE INSERT ON ROUTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VAISHALI"."ROUTE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TICKET_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "VAISHALI"."TICKET_TRG" 
BEFORE INSERT ON TICKET 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VAISHALI"."TICKET_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table FARE
--------------------------------------------------------

  ALTER TABLE "VAISHALI"."FARE" MODIFY ("ROUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."FARE" ADD CONSTRAINT "FARE_PK" PRIMARY KEY ("ROUTE_ID", "PLANE_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VAISHALI"."FARE" MODIFY ("PLANE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."FARE" MODIFY ("ECONOMY_FARE" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."FARE" MODIFY ("BUSINESS_FARE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLANE
--------------------------------------------------------

  ALTER TABLE "VAISHALI"."PLANE" MODIFY ("PLANE_ID" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."PLANE" MODIFY ("PLANE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."PLANE" ADD CONSTRAINT "PLANE_PK" PRIMARY KEY ("PLANE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROUTE
--------------------------------------------------------

  ALTER TABLE "VAISHALI"."ROUTE" MODIFY ("ROUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."ROUTE" MODIFY ("STARTING_FROM" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."ROUTE" MODIFY ("DESTINATION" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."ROUTE" ADD CONSTRAINT "ROUTE_PK" PRIMARY KEY ("ROUTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SEATING
--------------------------------------------------------

  ALTER TABLE "VAISHALI"."SEATING" MODIFY ("SEAT_NO" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."SEATING" MODIFY ("FLIGHT_ID" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."SEATING" MODIFY ("DEPT_TIME" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."SEATING" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."SEATING" ADD CONSTRAINT "SEATING_PK" PRIMARY KEY ("SEAT_NO", "FLIGHT_ID", "DEPT_TIME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "VAISHALI"."CUSTOMER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."CUSTOMER" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."CUSTOMER" MODIFY ("CUSTOMER_NAME" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."CUSTOMER" MODIFY ("CUSTOMER_PH" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."CUSTOMER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."CUSTOMER" MODIFY ("SSN" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "VAISHALI"."EMPLOYEE" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."EMPLOYEE" MODIFY ("EMPLOYEE_NAME" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."EMPLOYEE" MODIFY ("PHONE_NO" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."EMPLOYEE" MODIFY ("JOB_TITLE" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."EMPLOYEE" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VAISHALI"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_UK1" UNIQUE ("PHONE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FLIGHT
--------------------------------------------------------

  ALTER TABLE "VAISHALI"."FLIGHT" MODIFY ("FLIGHT_ID" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."FLIGHT" MODIFY ("ROUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."FLIGHT" MODIFY ("PLANE_ID" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."FLIGHT" MODIFY ("ARR_TIME" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."FLIGHT" MODIFY ("DEPT_TIME" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."FLIGHT" ADD CONSTRAINT "FLIGHT_PK" PRIMARY KEY ("FLIGHT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "VAISHALI"."TICKET" MODIFY ("TICKET_ID" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."TICKET" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."TICKET" MODIFY ("FLIGHT_ID" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."TICKET" MODIFY ("SEAT_NO" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."TICKET" MODIFY ("DOJ" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."TICKET" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."TICKET" MODIFY ("PASSENGER" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."TICKET" MODIFY ("SSN" NOT NULL ENABLE);
  ALTER TABLE "VAISHALI"."TICKET" ADD CONSTRAINT "BOOKING_PK" PRIMARY KEY ("TICKET_ID", "CUSTOMER_ID", "PASSENGER", "SSN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FARE
--------------------------------------------------------

  ALTER TABLE "VAISHALI"."FARE" ADD CONSTRAINT "FARE_FK1" FOREIGN KEY ("ROUTE_ID")
	  REFERENCES "VAISHALI"."ROUTE" ("ROUTE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FLIGHT
--------------------------------------------------------

  ALTER TABLE "VAISHALI"."FLIGHT" ADD CONSTRAINT "FLIGHT_FK1" FOREIGN KEY ("ROUTE_ID")
	  REFERENCES "VAISHALI"."ROUTE" ("ROUTE_ID") ENABLE;
  ALTER TABLE "VAISHALI"."FLIGHT" ADD CONSTRAINT "FLIGHT_FK2" FOREIGN KEY ("PLANE_ID")
	  REFERENCES "VAISHALI"."PLANE" ("PLANE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEATING
--------------------------------------------------------

  ALTER TABLE "VAISHALI"."SEATING" ADD CONSTRAINT "SEATING_FK1" FOREIGN KEY ("FLIGHT_ID")
	  REFERENCES "VAISHALI"."FLIGHT" ("FLIGHT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "VAISHALI"."TICKET" ADD CONSTRAINT "BOOKING_FK1" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "VAISHALI"."CUSTOMER" ("CUSTOMER_ID") ENABLE;
  ALTER TABLE "VAISHALI"."TICKET" ADD CONSTRAINT "BOOKING_FK3" FOREIGN KEY ("FLIGHT_ID")
	  REFERENCES "VAISHALI"."FLIGHT" ("FLIGHT_ID") ENABLE;
